apiVersion: v1
kind: Namespace
metadata:
  name: mtls-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: mtls-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
  namespace: mtls-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mtls-app
  namespace: mtls-app
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mtls-app
  namespace: mtls-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mtls-app
subjects:
- kind: ServiceAccount
  name: server
  namespace: mtls-app
- kind: ServiceAccount
  name: client
  namespace: mtls-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-configmap
  namespace: mtls-app
data:
  ca.crt: |
    <CA Content>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: mtls-app
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: server
      containers:
        - name: server
          image: mattiasgees/simple-mtls-server:latest
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: "/spiffe"
            name: spiffe
          - name: ca-volume
            mountPath: /ca
            readOnly: true
          args:
          - -k=/spiffe/tls.key
          - -p=/spiffe/tls.crt
          - -c=/ca/ca.crt
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
      volumes:
        - name: spiffe
          csi:
            driver: spiffe.csi.cert-manager.io
            readOnly: true
        - name: ca-volume
          configMap:
            name: ca-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: mtls-app
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: mtls-app
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: client
      containers:
        - name: server
          image: mattiasgees/simple-mtls-client:latest
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: "/spiffe"
            name: spiffe
          - name: ca-volume
            mountPath: /ca
            readOnly: true
          args:
          - -k=/spiffe/tls.key
          - -p=/spiffe/tls.crt
          - -c=/ca/ca.crt
          - -s=https://server.mtls-app.svc.cluster.local/hello
      volumes:
        - name: spiffe
          csi:
            driver: spiffe.csi.cert-manager.io
            readOnly: true
        - name: ca-volume
          configMap:
            name: ca-configmap
